-- 000008_create_events_and_registrations.up.sql

-- 1. Table Events (Scalable & Dynamic Schema)
CREATE TABLE IF NOT EXISTS events (
    id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    long_description TEXT,
    series_id VARCHAR(100),
    series_name VARCHAR(150),
    category_name VARCHAR(100) NOT NULL,
    category_variant VARCHAR(50) NOT NULL DEFAULT 'primary',
    event_date DATE NOT NULL,
    date_day VARCHAR(10) NOT NULL,
    date_month VARCHAR(20) NOT NULL,
    date_year VARCHAR(10) NOT NULL,
    date_full_text VARCHAR(150) NOT NULL,
    time VARCHAR(100) NOT NULL,
    location_name VARCHAR(255) NOT NULL,
    location_room VARCHAR(255),
    location_address TEXT,
    location_type VARCHAR(50) NOT NULL DEFAULT 'offline',
    cover_image TEXT NOT NULL,
    quota_total INT NOT NULL DEFAULT 50,
    quota_filled INT NOT NULL DEFAULT 0,
    quota_status VARCHAR(50) NOT NULL DEFAULT 'open',
    quota_status_label VARCHAR(100) NOT NULL DEFAULT 'Pendaftaran Terbuka',
    registration_url TEXT,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_free BOOLEAN NOT NULL DEFAULT TRUE,
    price BIGINT NOT NULL DEFAULT 0,
    payment_info JSONB NOT NULL DEFAULT '{}'::jsonb,
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    custom_fields_schema JSONB NOT NULL DEFAULT '[]'::jsonb,
    speakers JSONB NOT NULL DEFAULT '[]'::jsonb,
    rundown JSONB NOT NULL DEFAULT '[]'::jsonb,
    benefits JSONB NOT NULL DEFAULT '[]'::jsonb,
    prerequisites JSONB NOT NULL DEFAULT '[]'::jsonb,
    target_audience TEXT,
    registration_deadline VARCHAR(100),
    fee VARCHAR(100) NOT NULL DEFAULT 'Gratis',
    contact_person JSONB,
    status VARCHAR(50) NOT NULL DEFAULT 'published',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_slug ON events(slug);
CREATE INDEX IF NOT EXISTS idx_events_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_status ON events(status);
CREATE INDEX IF NOT EXISTS idx_events_featured ON events(featured);
CREATE INDEX IF NOT EXISTS idx_events_series_id ON events(series_id);

-- 2. Table Event Registrations
CREATE TABLE IF NOT EXISTS event_registrations (
    id VARCHAR(64) PRIMARY KEY,
    registration_code VARCHAR(64) UNIQUE NOT NULL,
    event_id VARCHAR(64) NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    full_name VARCHAR(150) NOT NULL,
    identity_number VARCHAR(100),
    institution VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    notes TEXT,
    answers JSONB NOT NULL DEFAULT '{}'::jsonb,
    uploaded_files JSONB NOT NULL DEFAULT '[]'::jsonb,
    payment_proof_url TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'pending_review', -- pending_review, needs_revision, approved, rejected, attended, cancelled
    admin_notes TEXT,
    verified_by UUID REFERENCES users(id) ON DELETE SET NULL,
    verified_at TIMESTAMPTZ,
    attended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_event_user_registration UNIQUE (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_event_reg_event_id ON event_registrations(event_id);
CREATE INDEX IF NOT EXISTS idx_event_reg_user_id ON event_registrations(user_id);
CREATE INDEX IF NOT EXISTS idx_event_reg_code ON event_registrations(registration_code);
CREATE INDEX IF NOT EXISTS idx_event_reg_status ON event_registrations(status);

-- 3. Register Granular Event Permissions
INSERT INTO permissions (id, name, module, description) VALUES
('events:read', 'View Events', 'events', 'Ability to view events and attendee lists'),
('events:create', 'Create Event', 'events', 'Ability to create new events and workshops'),
('events:update', 'Update Event', 'events', 'Ability to edit event details and quota'),
('events:delete', 'Delete Event', 'events', 'Ability to delete events'),
('events:manage', 'Manage Events', 'events', 'Ability to manage event attendees and status')
ON CONFLICT (id) DO NOTHING;

-- Assign permissions to Admin & Manager
INSERT INTO role_permissions (role_id, permission_id) VALUES
('admin', 'events:read'),
('admin', 'events:create'),
('admin', 'events:update'),
('admin', 'events:delete'),
('admin', 'events:manage'),
('manager', 'events:read'),
('manager', 'events:create'),
('manager', 'events:update'),
('manager', 'events:manage')
ON CONFLICT DO NOTHING;

-- 4. Seed Official UCH Events
INSERT INTO events (
    id, title, slug, description, long_description,
    series_id, series_name,
    category_name, category_variant, event_date,
    date_day, date_month, date_year, date_full_text,
    time, location_name, location_room, location_address, location_type,
    cover_image, quota_total, quota_filled, quota_status, quota_status_label,
    featured, is_free, price, payment_info, requires_approval, custom_fields_schema,
    fee, registration_deadline, target_audience,
    speakers, rundown, benefits, prerequisites, contact_person, status
) VALUES
(
    'demo-day-startup-pitch-2026',
    'UCH Demo Day & Startup Pitch Fest 2026',
    'uch-demo-day-dan-startup-pitch-fest-2026',
    'Ajang unjuk karya dan pitching produk inovasi mahasiswa di hadapan investor, akselerator, dan mitra industri nasional.',
    'UCH Demo Day & Startup Pitch Fest 2026 adalah puncak program akselerasi inovasi mahasiswa Universitas Teknologi Yogyakarta. Para finalis dari berbagai fakultas akan mempresentasikan produk inovatif mereka—mulai dari platform AI, solusi energi terbarukan, hingga teknologi agrikultur presisi—di hadapan dewan juri yang terdiri dari investor ventura, pimpinan inkubator bisnis, dan mitra industri teknologi terkemuka di Indonesia.',
    'innovation-accelerator-2026', 'Program Akselerasi Inovasi UTY 2026',
    'Demo Day & Pitching', 'primary', '2026-10-28',
    '28', 'OKT', '2026', 'Rabu, 28 Oktober 2026',
    '08:30 - 16:00 WIB', 'Auditorium Kampus 1 UTY', 'Lantai 3 Gedung Pusat Inovasi',
    'Jl. Siliwangi (Ringroad Utara), Jombor, Sleman, D.I. Yogyakarta', 'hybrid',
    '/images/porto2.jpeg', 120, 85, 'open', 'Pendaftaran Dibuka',
    TRUE, TRUE, 0, '{}'::jsonb, FALSE,
    '[{"key":"team_name","label":"Nama Tim / Startup (Jika Ada)","type":"text","required":false,"placeholder":"Contoh: Kreanovasi AI Lab"},{"key":"track","label":"Track Inovasi yang Diminati","type":"select","required":true,"options":["Smart Hardware & IoT","Software & Digital AI","Creative Design & Multimedia"]}]'::jsonb,
    'Gratis (Terbuka untuk Umum & Sivitas UTY)', '27 Oktober 2026, 23:59 WIB',
    'Mahasiswa UTY, founder startup muda, dosen pembimbing, serta pegiat industri teknologi dan investor ventura.',
    '[{"name":"Dr. Ir. Bambang Hendratmo, M.Kom.","role":"Direktur Inovasi & Inkubasi Bisnis","institution":"Universitas Teknologi Yogyakarta"},{"name":"Ahmad Farhan, M.Eng.","role":"Partner & Investment Lead","institution":"Nusantara Seed Venture"},{"name":"Laras Kirana, S.Ds.","role":"Head of Product Innovation","institution":"Karya Solusi Nusantara"}]'::jsonb,
    '[{"time":"08:30 - 09:00","activity":"Registrasi Peserta & Check-in","details":"Pengambilan name tag dan berkas agenda acara di meja registrasi."},{"time":"09:00 - 09:30","activity":"Opening Remarks & Keynote","speaker":"Dr. Ir. Bambang Hendratmo, M.Kom.","details":"Arah ekosistem kewirausahaan dan hilirisasi riset mahasiswa UTY."},{"time":"09:30 - 12:00","activity":"Pitching Sesi 1: Kategori Smart Hardware & IoT","details":"Presentasi 6 tim inovator dengan durasi 10 menit pitch dan 5 menit Q&A dewan juri."},{"time":"12:00 - 13:15","activity":"Istirahat, Sholat & Networking Lunch","details":"Pameran mini booth prototipe karya mahasiswa di selasar auditorium."},{"time":"13:15 - 15:15","activity":"Pitching Sesi 2: Kategori Software & Digital Solution","details":"Presentasi 6 tim inovator kategori aplikasi web, AI, dan platform digital."},{"time":"15:15 - 16:00","activity":"Awarding Ceremony & Investor Networking","details":"Pengumuman inovator terbaik, seed funding, dan penutupan acara."}]'::jsonb,
    '["Akses eksklusif menyaksikan 12 tim inovator mempresentasikan produk teruji","Sesi jejaring langsung bersama investor ventura dan inkubator bisnis","E-Sertifikat resmi kehadiran dari UTY Creative Hub","Akses booth pameran prototipe perangkat keras dan demonstrasi software","Paket konsumsi dan seminar kit resmi"]'::jsonb,
    '["Terbuka untuk mahasiswa aktif seluruh program studi UTY dan tamu undangan industri","Melakukan pendaftaran online dan menunjukkan e-tiket QR saat kedatangan","Berpakaian rapi dan sopan (kemeja atau batik formal)"]'::jsonb,
    '{"name":"Rizky Pratama","role":"Koordinator Acara Demo Day","phone":"+62 812-3456-7890","email":"creativehub@uty.ac.id"}'::jsonb,
    'published'
),
(
    'fastlab-iot-ai-esp32-workshop',
    'Workshop FastLab: Prototyping Smart IoT & AI',
    'workshop-fastlab-prototyping-iot-dan-ai-dengan-esp32',
    'Hands-on workshop perancangan hardware cerdas berbasis sensor pintar dan integrasi cloud di Laboratorium Prototyping UCH.',
    'Workshop intensif FastLab ini dirancang khusus untuk mahasiswa yang ingin mendalami pembuatan prototipe hardware cerdas. Peserta akan dibimbing langsung oleh mentor lab dalam merakit modul ESP32, mengintegrasikan berbagai modul sensor (lingkungan, jarak, dan kamera mikro), hingga menghubungkan data sensor ke platform dashboard berbasis IoT Cloud dengan inferensi model AI tepi (edge AI).',
    'fastlab-series-2026', 'FastLab Maker Series',
    'Hands-on Workshop', 'secondary', '2026-11-12',
    '12', 'NOV', '2026', 'Kamis, 12 November 2026',
    '09:00 - 13:00 WIB', 'Laboratorium FastLab UCH', 'Ruang Prototyping Hardware Lt. 2',
    'Jl. Siliwangi (Ringroad Utara), Jombor, Sleman, D.I. Yogyakarta', 'offline',
    '/images/room1.jpeg', 30, 18, 'open', 'Pendaftaran Dibuka',
    TRUE, TRUE, 0, '{}'::jsonb, FALSE,
    '[{"key":"laptop_os","label":"Sistem Operasi Laptop","type":"select","required":true,"options":["Windows 11 / 10","macOS (Apple Silicon / Intel)","Linux (Ubuntu / Fedora / Arch)"]},{"key":"arduino_installed","label":"Sudah install Arduino IDE 2.x?","type":"select","required":true,"options":["Sudah siap","Belum, butuh bantuan instalasi"]}]'::jsonb,
    'Gratis (Termasuk Peminjaman Hardware Kit Selama Sesi)', '10 November 2026, 17:00 WIB',
    'Mahasiswa Informatika, Teknik Elektro, Sistem Komputer, dan mahasiswa yang sedang mempersiapkan PKM-KC atau tugas akhir hardware.',
    '[{"name":"Yusuf Wicaksono, S.T., M.Eng.","role":"Lead Hardware Engineer FastLab","institution":"UTY Creative Hub"},{"name":"Dian Anggraini, S.Kom.","role":"Embedded Systems & AI Specialist","institution":"Laboratorium FastLab UTY"}]'::jsonb,
    '[{"time":"09:00 - 09:20","activity":"Pengantar Arsitektur ESP32 & Setup Toolchain","details":"Instalasi compiler ESP-IDF/Arduino IDE dan driver USB serial."},{"time":"09:20 - 10:45","activity":"Hands-on Praktikum 1: Interfacing Sensor & Aktuator","details":"Pembacaan sensor analog/digital dan kontrol aktuator melalui GPIO."},{"time":"10:45 - 11:00","activity":"Coffee Break & Diskusi Teknis","details":"Istirahat singkat dan konsultasi kendala kabel serta pemetaan pin."},{"time":"11:00 - 12:30","activity":"Hands-on Praktikum 2: Telemetri MQTT & Integrasi Cloud Dashboard","details":"Pengiriman data waktu-nyata ke broker MQTT dan visualisasi dasbor data."},{"time":"12:30 - 13:00","activity":"Review Project & Sesi Tanya Jawab","details":"Ulasan hasil implementasi peserta dan panduan peminjaman fasilitas FastLab mandiri."}]'::jsonb,
    '["Kit praktikum ESP32 lengkap (board, breadboard, sensor kit) disediakan selama acara","Akses berkelanjutan ke workstation pengujian FastLab untuk proyek lanjutan","Source code starter pack dan modul panduan PDF praktikum","E-Sertifikat keahlian praktis dari UTY Creative Hub","Konsumsi ringan dan sertifikat pendukung SKPI"]'::jsonb,
    '["Membawa laptop pribadi dengan sistem operasi Windows, Linux, atau macOS","Memiliki pemahaman dasar logika pemrograman (C/C++ atau Python dasar)","Telah menginstal software Arduino IDE 2.x sebelum hadir di sesi"]'::jsonb,
    '{"name":"Fajar Nugraha","role":"Laboran FastLab UTY","phone":"+62 821-9876-5432","email":"fastlab@uty.ac.id"}'::jsonb,
    'published'
),
(
    'masterclass-ai-venture-building-2026',
    'Masterclass AI & Venture Building: Riset Menuju Valuasi Seri-A',
    'masterclass-ai-venture-building-riset-menuju-valuasi-seri-a',
    'Masterclass intensif membedah validasi model AI, strategi komersialisasi riset universitas, dan struktur pitching ke investor venture capital.',
    'Didesain khusus untuk mahasiswa dan civitas akademika yang ingin mengubah riset kecerdasan buatan menjadi startup bernilai komersial tinggi. Peserta akan dibimbing langsung oleh partner venture capital dan praktisi AI terkemuka tentang product-market fit, unit economics, hingga pembuatan data room investasi.',
    'venture-series', 'Venture Mastery Series',
    'Masterclass & Bootcamp', 'accent', '2026-11-21',
    '21', 'NOV', '2026', 'Sabtu, 21 November 2026',
    '09:00 - 16:30 WIB', 'Think-Tank Space Kampus 1 UTY', 'Ruang Kolaborasi Lt. 1',
    'Jl. Siliwangi (Ringroad Utara), Jombor, Sleman, D.I. Yogyakarta', 'hybrid',
    '/images/porto1.jpeg', 50, 22, 'open', 'Pendaftaran Dibuka',
    TRUE, FALSE, 75000,
    '{"bank_name":"Bank Mandiri","account_number":"137-00-1928374-1","account_holder":"UTY Creative Hub Kreanovasi","qris_image_url":"/images/qris-dummy.png","instructions":"Transfer biaya pendaftaran Rp 75.000 ke rekening Bank Mandiri a.n UTY Creative Hub Kreanovasi atau via QRIS resmi UCH. Unggah bukti transfer pada formulir pendaftaran."}'::jsonb,
    FALSE,
    '[{"key":"startup_stage","label":"Tahap Produk Saat Ini","type":"select","required":true,"options":["Ide / Konsep","Prototipe / MVP","Sudah Berjalan / Memiliki Pengguna"]},{"key":"pitch_deck","label":"Unggah Draf Pitch Deck (Opsional, PDF)","type":"file","required":false,"accept":".pdf"}]'::jsonb,
    'Rp 75.000 (Early Bird Mahasiswa & Umum)', '19 November 2026, 23:59 WIB',
    'Founder startup mahasiswa, peneliti AI/Data Science, pengembang piranti lunak, dan pegiat venture building.',
    '[{"name":"Kevin Sanjaya, M.Sc.","role":"Principal Venture Partner","institution":"Horizon Ventures Southeast Asia"},{"name":"Dr. Amanda Saraswati","role":"Head of Applied AI Research","institution":"Karya Cipta AI Lab"}]'::jsonb,
    '[{"time":"09:00 - 09:30","activity":"Registrasi Peserta & Welcome Coffee","details":"Check-in peserta dan pembagian materi masterclass kit."},{"time":"09:30 - 12:00","activity":"Sesi 1: Menemukan Product-Market Fit untuk Model AI","speaker":"Dr. Amanda Saraswati","details":"Mengevaluasi kesiapan teknologi dan pemetaan kebutuhan pasar."},{"time":"12:00 - 13:00","activity":"Networking Lunch & Diskusi Santai","details":"Makan siang bersama pembicara dan sesama founder peserta."},{"time":"13:00 - 15:30","activity":"Sesi 2: Unit Economics, Valuasi & Pitching Deck Ventura","speaker":"Kevin Sanjaya, M.Sc.","details":"Studi kasus dekonstruksi pitch deck Seri-A dan simulasi term sheet."},{"time":"15:30 - 16:30","activity":"1-on-1 Office Hour & Mentoring Eksklusif","details":"Konsultasi tatap muka langsung rencana pitch deck tim."}]'::jsonb,
    '["Mentoring langsung 1-on-1 dengan Principal Venture Capital","Akses template pitch deck dan finansial model standar internasional","E-Sertifikat resmi bersertifikasi UTY Creative Hub","Makan siang prasmanan dan coffee break 2 sesi"]'::jsonb,
    '["Membawa laptop pribadi untuk sesi bedah finansial model","Memiliki ide atau prototipe produk digital (opsional tapi disarankan)"]'::jsonb,
    '{"name":"Rizky Pratama","role":"Koordinator Program Inkubasi","phone":"+62 812-3456-7890","email":"creativehub@uty.ac.id"}'::jsonb,
    'published'
),
(
    'klinik-proposal-pkm-2026',
    'Klinik Proposal PKM: Bedah Ide Menuju PIMNAS',
    'klinik-proposal-pkm-bedah-ide-menuju-pimnas-2026',
    'Klinik pendampingan eksklusif bedah proposal ide kreatif bersama dosen pembimbing dan reviewer nasional PKM.',
    'Program Pengkreatifan Mahasiswa (PKM) adalah momentum strategis bagi mahasiswa UTY untuk mengharumkan almamater di ajang PIMNAS. Klinik proposal ini memfasilitasi tim mahasiswa yang telah memiliki draf awal atau ide proposal untuk dibedah secara komprehensif oleh dewan reviewer universitas: dari perumusan latar belakang masalah, ketepatan skema, metode pelaksanaan, hingga kelayakan anggaran biaya (RAB).',
    'pkm-center-series', 'Road to PIMNAS 2026',
    'Klinik & Mentoring', 'primary', '2026-10-04',
    '04', 'OKT', '2026', 'Minggu, 04 Oktober 2026',
    '13:00 - 17:00 WIB', 'Think-Tank Space Kampus 1', 'Ruang Kolaborasi Tim Lt. 1',
    'Jl. Siliwangi (Ringroad Utara), Jombor, Sleman, D.I. Yogyakarta', 'offline',
    '/images/coworking-space.jpg', 50, 32, 'open', 'Pendaftaran Ditutup',
    TRUE, TRUE, 0, '{}'::jsonb, TRUE,
    '[{"key":"pkm_scheme","label":"Skema PKM yang Diajukan","type":"select","required":true,"options":["PKM-RE (Riset Eksakta)","PKM-RSH (Riset Sosial Humaniora)","PKM-K (Kewirausahaan)","PKM-PM (Pengabdian Masyarakat)","PKM-PI (Penerapan Iptek)","PKM-KC (Karsa Cipta)","PKM-KI (Karya Inovatif)","PKM-VGK (Video Gagasan Konstruktif)"]},{"key":"proposal_title","label":"Judul Draf Proposal","type":"text","required":true,"placeholder":"Masukkan judul sementara draf proposal"},{"key":"proposal_file","label":"Upload Draf Proposal (PDF, maks 10MB)","type":"file","required":true,"accept":".pdf"}]'::jsonb,
    'Gratis untuk Seluruh Tim Mahasiswa UTY (Wajib Kurasi)', '02 Oktober 2026, 20:00 WIB',
    'Tim mahasiswa UTY lintas program studi yang sedang menyusun proposal PKM-RE, PKM-K, PKM-KC, PKM-PM, PKM-PI, atau PKM-VGK.',
    '[{"name":"Prof. Dr. Suryadi, M.Sc.","role":"Reviewer Nasional PKM Kemendiktisaintek","institution":"Tim Pembina Penalaran Mahasiswa"},{"name":"Nurul Hidayati, S.T., M.T.","role":"Koordinator PKM Center UTY","institution":"Universitas Teknologi Yogyakarta"}]'::jsonb,
    '[{"time":"13:00 - 13:30","activity":"Registrasi Tim & Pembagian Ruang Mentoring","details":"Check-in peserta dan pengelompokan tim berdasarkan skema PKM."},{"time":"13:30 - 14:30","activity":"Plenary Session: Anatomi Proposal Lolos Pendanaan & PIMNAS","speaker":"Prof. Dr. Suryadi, M.Sc.","details":"Bedah kriteria penilaian reviewer nasional dan kesalahan fatal penyusunan proposal."},{"time":"14:30 - 16:30","activity":"One-on-One Desk Evaluation & Clinic Review","details":"Review mendalam naskah proposal per tim bersama reviewer dan dosen pembimbing."},{"time":"16:30 - 17:00","activity":"Action Plan Revisi & Foto Bersama","details":"Penyusunan jadwal pendampingan tahap dua dan penutupan klinik."}]'::jsonb,
    '["Review langsung per halaman draf proposal dari reviewer nasional berpengalaman","Panduan perbaikan judul, latar belakang, dan justifikasi anggaran (RAB)","Surat rekomendasi pendampingan resmi dari PKM Center UTY","E-Sertifikat keikutsertaan klinik intensif"]'::jsonb,
    '["Wajib telah membentuk tim (3-5 mahasiswa) dan memiliki draf proposal minimal 60% selesai","Membawa cetak naskah proposal sebanyak 2 eksemplar dan file digital di laptop","Hadir tepat waktu bersama seluruh anggota tim utama"]'::jsonb,
    '{"name":"Nurul Hidayati","role":"Koordinator PKM Center UTY","phone":"+62 818-0123-4567","email":"pkmcenter@uty.ac.id"}'::jsonb,
    'published'
),
(
    'creative-talk-ui-ux-design-system',
    'Creative Talk: Membangun Design System untuk Skala Produk',
    'creative-talk-ui-ux-design-system-dan-product-scale',
    'Diskusi panel dan studi kasus implementasi design system digital dari tim produk industri untuk mempercepat kolaborasi desainer dan engineer.',
    'Dalam pengembangan produk digital modern, kecepatan dan konsistensi antarmuka adalah faktor krusial. Melalui sesi Creative Talk ini, praktisi desain produk dan front-end engineer akan membedah bagaimana merancang token desain, komponen atomik, hingga dokumentasi terpadu yang membuat alur serah terima (handoff) antara desainer dan programmer berjalan mulus dan efisien.',
    'creative-talks', 'Creative Talk Series',
    'Seminar & Tech Talk', 'secondary', '2026-11-18',
    '18', 'NOV', '2026', 'Rabu, 18 November 2026',
    '09:30 - 12:00 WIB', 'Coworking Space UTY Creative Hub', 'Ruang Diskusi Utama Lt. 1',
    'Jl. Siliwangi (Ringroad Utara), Jombor, Sleman, D.I. Yogyakarta', 'hybrid',
    '/images/porto1.jpeg', 80, 45, 'open', 'Pendaftaran Dibuka',
    FALSE, TRUE, 0, '{}'::jsonb, FALSE,
    '[{"key":"portfolio_link","label":"Link Portofolio / LinkedIn / Dribbble","type":"text","required":false,"placeholder":"https://dribbble.com/username"}]'::jsonb,
    'Gratis untuk Mahasiswa & Umum', '16 November 2026, 23:59 WIB',
    'Mahasiswa prodi Informatika, Sistem Informasi, Desain Komunikasi Visual, serta pegiat UI/UX dan frontend web.',
    '[{"name":"Galih Prasetya, S.Kom.","role":"Lead Product Designer","institution":"Kreatif Digital Studio"},{"name":"Siti Nurhaliza, S.T.","role":"Senior Frontend Engineer","institution":"TechVentures Asia"}]'::jsonb,
    '[{"time":"09:30 - 10:00","activity":"Registrasi & Sambutan Pengantar","details":"Pembukaan dan perkenalan topik evolusi design system modern."},{"time":"10:00 - 11:00","activity":"Sesi Inti: Anatomi Token Desain & Struktur Komponen Figma","speaker":"Galih Prasetya, S.Kom.","details":"Studi kasus pembuatan sistem warna, tipografi, dan varian komponen di Figma."},{"time":"11:00 - 11:45","activity":"Sesi Kolaborasi: Menjembatani Figma ke Kode (Tailwind & React)","speaker":"Siti Nurhaliza, S.T.","details":"Menerjemahkan token ke utilitas Tailwind CSS dan komponen React yang teruji."},{"time":"11:45 - 12:00","activity":"Tanya Jawab Interaktif & Foto Bersama","details":"Diskusi terbuka dengan para narasumber dan penyerahan cenderamata."}]'::jsonb,
    '["Studi kasus nyata arsitektur design system produk berskala jutaan pengguna","Akses file template Figma UI Kit dan dokumentasi komponen","E-Sertifikat resmi dari UTY Creative Hub","Peluang diskusi dan mentoring portofolio desain langsung bersama praktisi"]'::jsonb,
    '["Terbuka untuk umum dan sivitas akademika","Disarankan telah mengenal dasar alat desain Figma atau styling kode CSS"]'::jsonb,
    '{"name":"Danang Wijaya","role":"Divisi Program Komunitas UCH","phone":"+62 813-2468-1357","email":"community@uty.ac.id"}'::jsonb,
    'published'
),
(
    'bootcamp-rapid-mvp-development',
    'Bootcamp Kreanovasi: Rapid MVP Development',
    'bootcamp-kreanovasi-rapid-mvp-development-2026',
    'Program intensif 2 hari membangun Minimum Viable Product siap uji pasar menggunakan stack modern Next.js dan Supabase.',
    'Banyak ide inovasi mahasiswa terhenti di tahap gagasan karena lamanya proses pengembangan teknis. Bootcamp Kreanovasi memandu peserta membangun prototipe fungsional (MVP) dalam tempo 2 hari menggunakan Next.js App Router, Tailwind CSS, dan BaaS Supabase. Peserta diajarkan membuat alur autentikasi, manajemen basis data, integrasi API, hingga deployment otomatis ke cloud publik.',
    'kreanovasi-bootcamp', 'Bootcamp Intensif Kreanovasi',
    'Hands-on Workshop', 'primary', '2026-12-05',
    '05', 'DES', '2026', 'Sabtu - Minggu, 5 - 6 Desember 2026',
    '08:30 - 16:30 WIB', 'Laboratorium Multimedia Kampus 1', 'Lab Komputer 3 Lt. 3',
    'Jl. Siliwangi (Ringroad Utara), Jombor, Sleman, D.I. Yogyakarta', 'offline',
    '/images/room2.jpeg', 35, 15, 'open', 'Pendaftaran Dibuka',
    FALSE, FALSE, 50000,
    '{"bank_name":"Bank BCA","account_number":"846-5521-990","account_holder":"UTY Creative Hub Kreanovasi","qris_image_url":"/images/qris-dummy.png","instructions":"Transfer biaya pendaftaran Rp 50.000 ke rekening BCA a.n UTY Creative Hub Kreanovasi. Upload bukti transfer pada formulir."}'::jsonb,
    TRUE,
    '[{"key":"github_url","label":"Akun / Profil GitHub","type":"text","required":true,"placeholder":"https://github.com/username"},{"key":"tshirt_size","label":"Ukuran Kaos Peserta","type":"select","required":true,"options":["S","M","L","XL","XXL"]}]'::jsonb,
    'Rp 50.000 (Commitment Fee - Refundable saat Hadir)', '03 Desember 2026, 18:00 WIB',
    'Mahasiswa tingkat 2-4 yang sedang mengerjakan prototipe startup atau tugas akhir berbasis web aplikasi.',
    '[{"name":"Muhammad Ilham, S.Kom., M.T.","role":"Full-Stack Software Architect","institution":"Pusat Riset Perangkat Lunak UTY"}]'::jsonb,
    '[{"time":"08:30 - 10:00","activity":"Hari 1: Perumusan Ruang Lingkup MVP & Skema Database","details":"Teknik membatasi fitur produk esensial dan perancangan relasi data."},{"time":"10:00 - 12:00","activity":"Hari 1: Setup Proyek Next.js & Autentikasi Pengguna","details":"Konfigurasi autentikasi aman dengan row-level security (RLS)."},{"time":"13:00 - 16:30","activity":"Hari 1: Pembangunan Fitur Utama & Server Actions","details":"Pengelolaan CRUD fungsional tanpa backend boilerplate berlebih."},{"time":"08:30 - 12:00","activity":"Hari 2: Integrasi UI Interaktif & Pengujian Alur Pengguna","details":"Penyempurnaan antarmuka menggunakan komponen UI aksesibel."},{"time":"13:00 - 16:30","activity":"Hari 2: Deployment Cloud, Pengujian Beban & Demo Internal","details":"Proses publikasi aplikasi dan presentasi demo masing-masing kelompok."}]'::jsonb,
    '["Aplikasi web utuh yang siap dijadikan portofolio dan diuji ke target pengguna","Repository kode acuan lengkap dengan lisensi open source","E-Sertifikat kelulusan bootcamp bersertifikasi universitas","Konsumsi penuh selama 2 hari pelaksanaan"]'::jsonb,
    '["Menguasai dasar JavaScript / TypeScript dan konsep dasar HTML/CSS","Membawa laptop pribadi dengan Node.js versi LTS terinstal","Memiliki akun GitHub aktif"]'::jsonb,
    '{"name":"Taufik Hidayat","role":"Asisten Lab Multimedia UTY","phone":"+62 895-3344-5566","email":"labkomputer@uty.ac.id"}'::jsonb,
    'published'
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    long_description = EXCLUDED.long_description,
    series_id = EXCLUDED.series_id,
    series_name = EXCLUDED.series_name,
    category_name = EXCLUDED.category_name,
    category_variant = EXCLUDED.category_variant,
    event_date = EXCLUDED.event_date,
    date_day = EXCLUDED.date_day,
    date_month = EXCLUDED.date_month,
    date_year = EXCLUDED.date_year,
    date_full_text = EXCLUDED.date_full_text,
    time = EXCLUDED.time,
    location_name = EXCLUDED.location_name,
    location_room = EXCLUDED.location_room,
    location_address = EXCLUDED.location_address,
    location_type = EXCLUDED.location_type,
    cover_image = EXCLUDED.cover_image,
    quota_total = EXCLUDED.quota_total,
    quota_filled = EXCLUDED.quota_filled,
    quota_status = EXCLUDED.quota_status,
    quota_status_label = EXCLUDED.quota_status_label,
    featured = EXCLUDED.featured,
    is_free = EXCLUDED.is_free,
    price = EXCLUDED.price,
    payment_info = EXCLUDED.payment_info,
    requires_approval = EXCLUDED.requires_approval,
    custom_fields_schema = EXCLUDED.custom_fields_schema,
    fee = EXCLUDED.fee,
    registration_deadline = EXCLUDED.registration_deadline,
    target_audience = EXCLUDED.target_audience,
    speakers = EXCLUDED.speakers,
    rundown = EXCLUDED.rundown,
    benefits = EXCLUDED.benefits,
    prerequisites = EXCLUDED.prerequisites,
    contact_person = EXCLUDED.contact_person,
    status = EXCLUDED.status;
